# Configuration of Hugo
# Guide: https://docs.hugoblox.com/tutorial/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

title: nodove blog # Website name
baseURL: 'https://choisimo.github.io' # Website URL


############################
## LANGUAGE
############################

languages:
  ko:
    languageCode: ko
    languageName: Korean
    contentDir: content/ko
    weight: 1
    title: "nodove 블로그"
    pagination:
      disaableAliases: true
      pagerSize: 10          # Returns the number of pages per pager
      path: page
    menu:
      main:
        - name: "게시글"
          weight: 500
        - name: "최신"
          parent: "게시글"
          url: "/post/latest/"
          weight: 501
        - name: "리스트"
          parent: "게시글"
          url: "/post/"
          weight: 502
          
        - name: "저자"
          weight: 600
        - name: "세부내역"
          parent: "저자"
          url: "/about/"
          weight: 601
        - name: "연락방법"
          parent: "저자"
          url: "/contact"
          weight: 602
        - name: "맵"
          parent: "저자"
          url: "/about/#contact"
          weight: 603

        - name: "구분"
          weight: 700
        - name: "카테고리"
          url: "/categories"
          parent: "구분"
          weight: 701
        - name: "태그"
          url: "/tags"
          parent: "구분"
          weight: 702
        - name: "저자"
          url: "/author"
          parent: "구분"
          weight: 703

        - name: "자료"
          weight: 800
        - name: "프로그램"
          url: "/document/program"
          parent: "자료"
          weight: 801
        - name: "문서"
          url: "/document"
          parent: "자료"
          weight: 802

        - name: "엔터"
          weight: 900
        - name: "여가"
          url: "/entertainment"
          parent: "엔터"
          weight: 901
        - name: "게임"
          url: "/entertainment/game"
          parent: "엔터"
          weight: 902
        
        
          
  en:
    languageCode: en-us
    languageName: English
    contentDir: content/en
    weight: 2
    title: "nodove blog"
    pagination:
      disaableAliases: true
      pagerSize: 10          # Returns the number of pages per pager
      path: page
    menu:
      main:
        - name: "post"
          weight: 500
        - name: "latestPost"
          parent: "post"
          url: "/post/latest"
          weight: 501
        - name: "list"
          url: "/post/"
          parent: "post"
          weight: 502

        - name: "about"
          weight: 600
        - name: "author"
          parent: "about"
          url: "/about/"
          weight: 601
        - name: "contact"
          parent: "about"
          url: "/contact"
          weight: 602
          icon: "contact-icon"
        - name: "map"
          parent: "about"
          url: "/about/#contact"
          weight: 603

        - name: "category"
          weight: 700
        - name: "categories"
          url: "/categories"
          parent: "category"
          weight: 701
        - name: "tags"
          url: "/tags"
          parent: "category"
          weight: 702
        - name: "author"
          url: "/author"
          parent: "category"
          weight: 703

        - name: "document"
          weight: 800
        - name: "program"
          parent: "document"
          url: "/document/program"
          weight: 801
        - name: "documentation"
          url: "/document"
          parent: "document"
          weight: 802


        - name: "play"
          weight: 900
        - name: "entertainment"
          url: "/entertainment"
          parent: "play"
          weight: 901
        - name: "game"
          url: "/entertainment/game"
          parent: "play"
          weight: 902
        
            


defaultContentLanguage: ko
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true


############################
## ADVANCED
############################

enableGitInfo: false
summaryLength: 30
pagination:
  paperSize: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  authors: '/author/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
disableAliases: true
outputs:
  home: [HTML, RSS, JSON, WebAppManifest, headers, redirects]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 75
  anchor: smart
timeout: 600000
taxonomies:
  tag: tags
  category: categories
  author: authors
markup:
  _merge: deep
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70
security:
  _merge: deep
sitemap:
  _merge: deep
minify:
  _merge: deep
