# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/



# Default language
ko:
  languageCode: ko
  languageName: Korean
  contentDir: content/ko
  params:
    description: korean
  menu:
    main:
      - name: 메인
        url: '#main'
  weight: 1

en:
  languageCode: en-us
  languageName: English
  contentDir: content/en
  params:
    description: english-us
  weight: 2


# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
