# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/



# Default language
languages:
  ko:
    languageCode: ko
    languageName: Korean
    weight: 1
    params:
      menu:
        main:
          - name: "홈"
            url: "/ko/"
            weight: 1
  en:
    languageCode: en
    languageName: English
    weight: 2
    params:
      menu:
        main:
          - name: "Home"
            url: "/en/"
            weight: 1



# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
