ko:
  - name: "홈"
    url: "/"
    weight: 1
  - name: "소개"
    url: "/about/"
    weight: 2
  - name: "저자"
    url: "/ko/authors/admin/"
    weight: 3
  - name: "소개"
    url: "/ko/about/"
    weight: 4
en:
  - name: "Home"
    url: "/en/"
    weight: 1
  - name: "About"
    url: "/en/about/"
    weight: 2
  - name: "author"
    url: "/en/authors/admin"
    weight: 3
  - name: "about"
    url: "/en/about/"
    weight: 4   
