# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10

  - name: About
    url: /about/
    weight: 20
    
  - name: posts
    url: /post/
    weight: 30
  - parent: posts
    name: status
    url: /post/status/
    weight: 31
  - parent: posts
    name: newPosts
    url: /post/new/
    weight: 32


  - name: contacts
    url: /contact/
    weight: 40