ko:
  - name: "홈"
    url: "/"
    weight: 1
  - name: "소개"
    url: "/about/"
    weight: 2
en:
  - name: "Home"
    url: "en/"
    weight: 1
  - name: "About"
    url: "en/about/"
    weight: 2
    
